#!/bin/bash
#Author: wladypauly
#Mail: wladpaul@yahoo.com
echo "THIS SCRIPT IS MEANT TO BE RUN AFTER INSTALLING UBUNTU"
echo
echo "What this script does is the following:"
echo
echo "1. it adds some ppas I use, ppas you can see inside the script"
echo
echo "2. it installs a series of packages I use most"
echo
echo "At some point the script will ask for your password and/or to confirm with Y some actions" 
echo "Are you sure you want to continue? (Y/N)"
read a
if [ $a = "n" ] ; then
echo  "Operation aborted. See you! :)"
exit
fi
if [ $a = "y" ] ; then
#echo "The universe and multiverse repositories will be enabled now"
#sudo add-apt-repository "deb http://main.archive.ubuntu.com/ubuntu/ trusty universe multiverse"
#sudo add-apt-repository "deb http://main.archive.ubuntu.com/ubuntu/ trusty-updates universe multiverse"
echo "Now some ppas will be added"
sudo add-apt-repository -y ppa:linrunner/tlp #laptop tools
sudo add-apt-repository -y ppa:venerix/pkg #tvmaxe ppa
sudo add-apt-repository -y ppa:webupd8team/java #oracle-java ppa
sudo add-apt-repository -y ppa:otto-kesselgulasch/gimp #gimp
sudo add-apt-repository -y ppa:mc3man/trusty-media #ffmpeg
#sudo add-apt-repository -y ppa:danielrichter2007/grub-customizer #the name is self-explanatory
sudo add-apt-repository -y ppa:unit193/inxi #utility to display hardware details in terminal
sudo add-apt-repository -y ppa:tsbarnes/indicator-keylock #keyboard indicator for Caps Lock, Num Lock, Scroll Lock
sudo add-apt-repository -y ppa:ffmulticonverter/stable #multimedia and document format converter
sudo add-apt-repository -y ppa:teejee2008/ppa # aptik - a utility to backup and restore ppas, installed packages and more
sudo apt-get update
echo "Now the package laptop-mode-tools will be purged, as it conflicts with tlp-tools, a package specially designed for laptops, especially LENOVO laptops"
echo "Also, openjdk will be removed as a replacement - oraclejava - will be installed"
sudo apt-get purge laptop-mode-tools openjdk*
sudo apt-get autoremove
echo "Now the system will be updated. DO NOT restart the system after the update, wait for this script to finish and it will automatically reboot your system!!"
sudo apt-get dist-upgrade
echo
echo "Now some packages, some of them from the ppas, will be installed"
sudo apt-get install gimp gmic tlp tlp-rdw smartmontools ethtool tp-smapi-dkms acpi-call-tools tv-maxe oracle-java8-installer inxi indicator-keylock ffmulticonverter aptik libreoffice blender synaptic audacious audacity 
echo "Now the system will be cleaned of downloaded packages and then rebooted. MAKE SURE YOU CLOSE ALL APPLICATIONS AND SAVE ALL OF YOUR WORK BEFORE PROCEEDING!!"
echo "DO YOU WISH TO CONTINUE?"
read a
if [ $a = "n" ] ; then
echo  "Operation aborted. See you! :)"
exit
fi
if [ $a = "y" ] ; then
sudo apt-get clean && sudo apt-get autoclean
echo "SYSTEM IS ABOUT TO BE RESTARTED!"
sudo reboot
fi
fi
exit 0
